<table align="center" width=100%>
    <tr>
        <td width="12%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                    <b> Basic Python Programming <br>(Day 3)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/vidyadharbendre/learn_advanced_python_using_examples/blob/main/notebooks/Basics/basic_python_programming_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
  <td>
    <a target="_blank" href="https://kaggle.com/kernels/welcome?src=https://github.com/vidyadharbendre/learn_advanced_python_using_examples/blob/main/notebooks/Basics/basic_python_programming_3.ipynb"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" /></a>
  </td>
</table>

## Table of Content

1. **[Python Flow Control](#flow_control)**
2. **[List Comprehension](#lc)**



### Let's begin with some hands-on practice exercises

<a id= "flow_control"> </a>
## 1. Python Flow Control

<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a code to print table of 5 using assignment operand +=.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [2]:
#1. Write a code to print table of 5 using assignment operand +=.
# type your code here
a = 0
for i in range(1, 11):
    a += 5
    print('5', 'X', i, '=',  a)




5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
5 X 10 = 50


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Write a program for generating a fibonacci series starting with 0 and 1 for the next 10 values using a while loop. </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [3]:
#2. Write a program for generating a fibonacci series starting with 0 and 1 for the next 10 values 
#using a while loop.
# type your code here  


# first two terms
num1, num2 = 0, 1
count = 0

while count < 12:
    print(num1)
    total = num1 + num2
    # update values
    num1 = num2
    num2 = total
    count += 1



0
1
1
2
3
5
8
13
21
34
55
89


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a program to check whether a number is greater than the other using if statement (take the input from user).</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [69]:
#3. Write a program to check whether a number is greater than the other using 
#if statement (take the input from user).
# type your code here

n1 = input("Enter the first number :")
n2 = input ("Enter the second number :")

if (n1 > n2):
    print("First number entered {} is greater than the second number {}".format(n1, n2))
else:
    print("First number entered {} is not greater than the second number {}".format(n1, n2))


Enter the first number12
Enter the second number45
First number entered 12 is not greater than the second number 45


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a code to check whether a number is divisible by 7 or not (take the input from user). </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [5]:
#4. Write a code to check whether a number is divisible by 7 or not (take the input from user).
# type your code here

num_div = int(input("Enter a number to see it is divisble by 7 or not"))
if (num_div % 7) == 0:
    print("The entered number {} is divisible by 7".format(num_div))
else:
    print("The entered number {} is NOT divisible by 7".format(num_div))

    



Enter a number to see it is divisble by 7 or not8
The entered number 8 is NOT divisible by 7


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a code to find factorial of a number (take the input from user). </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [6]:
#5. Write a code to find factorial of a number (take the input from user).
# type your code here

fact_input = int(input("Enter a number to find factorial :"))
fact_total = 1

for i in range(fact_input, 1, -1):
    fact_total *= i

print(fact_total)



Enter a number to find factorial :5
120


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to check whether a number is prime or not (take the input from user).</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [7]:
#6. Write a program to check whether a number is prime or not (take the input from user).
# type your code here

prime_num = int(input("Enter a number to check wheather is prime or not"))

def isPrime(num):  #  return True if the num is prime else return False
    if num < 2:
        return False
       
    for div in range(2, round(num**0.5)+1):
        if num % div == 0:
            return False
            
    return True


if isPrime(prime_num):
    print("The entered number {} is a prime number".format(prime_num))
else:
    print("The entered number {} is not a prime number".format(prime_num))






Enter a number to check wheather is prime or not5
The entered number 5 is a prime number


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a program to check whether two numbers are amicable or not (take the input from user).</b>
                </font>
            </div>
        </td>
    </tr>
</table>

7. Write a program to check whether two numbers are amicable or not (take the input from user).

In [8]:
#7. Write a program to check whether two numbers are amicable or not (take the input from user).
# type your code here


# find the divisors!

def findSumDivisors(num):
    sum = 0
    for i in range(1, num):
        if num % i == 0:
            sum += i
#        print(sum)
    return sum

num1 = int(input("Enter a first number"))
num2 = int(input("Enter a second number"))

sum1 = findSumDivisors(num1)
print(sum1, num2)

sum2 = findSumDivisors(num2)
print(sum2, num1)

if (sum1 == num2) and sum2 == num1:
    print("The entered first number {} and the second number {} are amicable".format(num1, num2))
else:
    print("The entered first number {} and the second number {} are not amicable".format(num1, num2))


Enter a first number4
Enter a second number6
3 6
6 4
The entered first number 4 and the second number 6 are not amicable


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Reverse string using a for loop (take the input from user).</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [9]:
#8. Reverse string using a for loop (take the input from user).
# type your code here

input_string = input("Enter a string")
reverse_string = " "

# other_string = input_string[::-1]
# print(other_string)

for i in range(1, len(input_string)+1):
    
    reverse_string = reverse_string + input_string[-i]
    
print(input_string, reverse_string)

Enter a stringRAR
RAR  RAR


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a code to find the average of given numbers (take the input from user).</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [10]:
#9. Write a code to find the average of given numbers (take the input from user).
# type your code here

total_num = int(input("How many numbers that you want to take an average"))

num_sum = 0
n = 0
while (n < total_num):
    n += 1
    num = int(input("Enter the {} number - one by one by hitting enter key :".format(n)))
    num_sum += num
print("Average :", num_sum/total_num)


How many numbers that you want to take an average3
Enter the 1 number - one by one by hitting enter key :1
Enter the 2 number - one by one by hitting enter key :2
Enter the 3 number - one by one by hitting enter key :3
Average : 2.0


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to find the area of a circle for a given radius (take the input from user).</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [46]:
#10. Write a program to find the area of a circle for a given radius (take the input from user).
# type your code here
# pi * r * r

pi = round(22/7, 2)
r = int(input("Enter the raidus of the circle to find out the area of the circle "))
area = pi * r * r
print("The area of the circle is {} for the given radius {} ".format(round(area,2), r))




Enter the raidus of the circle to find out the area of the circle 2
The area of the circle is 12.56 for the given radius 2 


In [36]:
22/7

3.142857142857143

<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a code to find the simple interest (take the input from user).</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [11]:
#11. Write a code to find the simple interest (take the input from user).
# type your code here

def simpIntCal(p, t, r):
    return (p * t * r)/100

p = float(input("Enter principla amount :"))
r = float(input("Enter rate of interest :"))
t = float(input("Enter time period in years :"))

simple_interest = simpIntCal(10000, 8, 1)
print("simple interest :", simple_interest)

simple_interest = simpIntCal(p, t, r)
print("simple interest :", simple_interest)




Enter principla amount :1000
Enter rate of interest :8
Enter time period in years :1
simple interest : 800.0
simple interest : 80.0


<a id= "lc"> </a>
## 2. List Comprehension

<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Use list comprehension to obtain the squre root of first 10 natural numbers.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [12]:
#12. Use list comprehension to obtain the squre root of first 10 natural numbers.
# type your code here

sqrt_num = [ round(i**0.5,2) for i in range(1, 10)]
print(sqrt_num)




[1.0, 1.41, 1.73, 2.0, 2.24, 2.45, 2.65, 2.83, 3.0]


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Use list comprehension to find the used vowels in a given sentence and/or word (take the input from user). </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [13]:
#13. Use list comprehension to find the used vowels in a given sentence and/or word (take the input from user).
# type your code here

input_user = input("Enter sentence or word to know the vowels in it   : ")
vowels = 'aeiouAEIOU'

output_vowel = [ ch for ch in input_user if ch in vowels]
print(output_vowel)


Enter sentence or word to know the vowels in it   : Vidyadhar Bendre
['i', 'a', 'a', 'e', 'e']


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Create a dictionary and access it values using a condition on its key. The data is given below. Let the condidtion on the key is that it should be a even number.</b>
                </font>
            </div>
       </td>
    </tr>
</table>


<table>
<tr>
    <th>Key</th>
    <td>1</td>
    <td>2</td>
    <td>3</td>
    <td>4</td> 
    <td>5</td> 
</tr>
<tr>
    <th>Name</th>
    <td>Aman</td>
    <td>Mohit</td>
    <td>Guari</td>
    <td>Imran</td>
    <td>Roma</td
     </tr>
<tr>
    <th>Marks</th>
    <td>24</td>
    <td>25</td>
    <td>26</td>
    <td>24</td>
    <td>27</td>
   </tr>
</table>

In [15]:
#14. Create a dictionary and access it values using a condition on its key. The data is given below. Let the condidtion on the key is that it should be a even number.
# type your code here


students = {1:{'Name': 'Arman', 'Marks': 24}, 2:{'Name': 'Mohit', 'Marks': 25}, 3:{'Name':'Gauri', 'Marks':26}, 4:{'Name':'Imran', 'Marks': 24}, 5: {'Name': 'Roma', 'Marks': 27}}

for key, values in students.items():
    if key % 2 == 0:
        print(students[key])

even_students = {key:values for key, values in students.items()  if key % 2 == 0 }
print(even_students)

{'Name': 'Mohit', 'Marks': 25}
{'Name': 'Imran', 'Marks': 24}
{2: {'Name': 'Mohit', 'Marks': 25}, 4: {'Name': 'Imran', 'Marks': 24}}


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Use list comprehension to find even and odd numbers from first 20 whole numbers.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [16]:
#15. Use list comprehension to find even and odd numbers from first 20 whole numbers.
# type your code here


odd_even_list = [(i, "Even number") if i % 2 == 0 else (i, "odd number") for i in range(20)]
print(odd_even_list)


[(0, 'Even number'), (1, 'odd number'), (2, 'Even number'), (3, 'odd number'), (4, 'Even number'), (5, 'odd number'), (6, 'Even number'), (7, 'odd number'), (8, 'Even number'), (9, 'odd number'), (10, 'Even number'), (11, 'odd number'), (12, 'Even number'), (13, 'odd number'), (14, 'Even number'), (15, 'odd number'), (16, 'Even number'), (17, 'odd number'), (18, 'Even number'), (19, 'odd number')]


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Use list comprehension to print numbers divisible  by 2 and 3 in between 1 and 100. </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [17]:
#16. Use list comprehension to print numbers divisible by 2 and 3 in between 1 and 100.
# type your code here


div_2_3_list = [ num  for num in range(1, 100) if (num % 2 == 0) and (num % 3 == 0) ]
print(div_2_3_list)


[6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96]


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Use list comprehension to create a dictionary such that its keys are numbers from 1 to 10 and values are the corresponding to that key are its cube.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [18]:
#17. Use list comprehension to create a dictionary such that its keys are numbers from 1 to 10 
#and values are the corresponding to that key are its cube.
# type your code here


l1 = [(num, num**3) for num in range(1, 11)]
print(l1)
d1 = { key : value for key, value in l1 }

print(d1)
     
d2 = { num: num**3   for num in range(1,11)}
print(d2)

[(1, 1), (2, 8), (3, 27), (4, 64), (5, 125), (6, 216), (7, 343), (8, 512), (9, 729), (10, 1000)]
{1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729, 10: 1000}
{1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729, 10: 1000}


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Use list comprehension to extract numbers from a string </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [19]:
#18. Use list comprehension to extract numbers from a string
# type your code here

input_string = 'Karnataka extends COVID-19 lockdown in 11 districts'

output_string = [i for i in input_string if i.isdigit()]
print(output_string)





['1', '9', '1', '1']


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Use list comprehension to print table of 11 to 20 as shown below.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

<table>
<tr>
    <td>11</td><td>22</td><td>33</td><td>44</td><td>55</td><td>66</td><td>77</td><td>88</td><td>99</td><td>110</td> 
</tr>
    
<tr>
    <td>12</td><td>24</td><td>36</td><td>48</td><td>60</td><td>72</td><td>84</td><td>96</td><td>108</td><td>120</td> 
</tr>

<tr>
    <td>13</td><td>36</td><td>39</td><td>52</td><td>65</td><td>78</td><td>91</td><td>104</td><td>117</td><td>130</td> 
</tr> 

<tr>
     <td>14</td><td>28</td><td>42</td><td>56</td><td>70</td> <td>84</td><td>98</td><td>112</td><td>126</td><td>140</td> 
</tr>

<tr>
     <td>15</td><td>30</td><td>45</td><td>60</td><td>75</td><td>90</td><td>105</td><td>120</td><td>135</td><td>150</td> 
</tr>

<tr>
     <td>16</td><td>32</td><td>48</td><td>64</td><td>80</td><td>96</td><td>112</td><td>128</td><td>144</td><td>160</td> 
</tr> 

<tr>
     <td>17</td><td>34</td><td>51</td><td>68</td><td>85</td><td>102</td><td>119</td><td>136</td><td>153</td><td>170</td> 
</tr> 

<tr>
     <td>18</td><td>36</td><td>54</td><td>72</td><td>90</td> <td>108</td><td>126</td><td>144</td><td>162</td><td>180</td> 
</tr>

<tr>
 <td>19</td><td>38</td><td>57</td><td>76</td><td>95</td><td>114</td><td>133</td><td>152</td><td>171</td><td>190</td> 
</tr>

<tr>
     <td>20</td><td>40</td><td>60</td><td>80</td><td>100</td><td>120</td><td>140</td><td>160</td><td>180</td><td>200</td> 
<tr>    
    
</table>

In [21]:
import numpy as np
#19. Use list comprehension to print table of 11 to 20 as shown below.
# type your code here

for i in range(11, 21): 
    for j in range(1, 11):
        print(i*j, end = ' ')
    print(end = '\n')


output_list = [ (i*j) for i in range(11, 21) for j in range(1, 11)] 
#print(output_list)

new_1 = np.array(output_list).reshape(10, 10)
print(new_1)

print('\n\n')

new_2 = np.array([ (i*j) for i in range(11, 21) for j in range(1, 11)]).reshape(10, 10)
print(new_2)


11 22 33 44 55 66 77 88 99 110 
12 24 36 48 60 72 84 96 108 120 
13 26 39 52 65 78 91 104 117 130 
14 28 42 56 70 84 98 112 126 140 
15 30 45 60 75 90 105 120 135 150 
16 32 48 64 80 96 112 128 144 160 
17 34 51 68 85 102 119 136 153 170 
18 36 54 72 90 108 126 144 162 180 
19 38 57 76 95 114 133 152 171 190 
20 40 60 80 100 120 140 160 180 200 
[[ 11  22  33  44  55  66  77  88  99 110]
 [ 12  24  36  48  60  72  84  96 108 120]
 [ 13  26  39  52  65  78  91 104 117 130]
 [ 14  28  42  56  70  84  98 112 126 140]
 [ 15  30  45  60  75  90 105 120 135 150]
 [ 16  32  48  64  80  96 112 128 144 160]
 [ 17  34  51  68  85 102 119 136 153 170]
 [ 18  36  54  72  90 108 126 144 162 180]
 [ 19  38  57  76  95 114 133 152 171 190]
 [ 20  40  60  80 100 120 140 160 180 200]]



[[ 11  22  33  44  55  66  77  88  99 110]
 [ 12  24  36  48  60  72  84  96 108 120]
 [ 13  26  39  52  65  78  91 104 117 130]
 [ 14  28  42  56  70  84  98 112 126 140]
 [ 15  30  45  60  75  90 105 120 135 150]
 [ 

<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>20. Use list comprehension to find transpose of the matrix given below.</b>
                </font>
            </div>
        </td>
    </tr>
</table>

<table>
    <tr>
        <td>1</td>
        <td>2</td>
    </tr>
    <tr>
        <td>3</td>
        <td>4</td>
    </tr>
    <tr>
        <td>5</td>
        <td>6</td>
    </tr>
    <tr>
        <td>7</td>
        <td>8</td>
    </tr>
    </table>

In [22]:
#20. Use list comprehension to find transpose of the matrix given below.
# type your code here

matrix = np.array([[1,2],[3,4],[5,6],[7,8]])
print(matrix)
print("\n")
print(matrix.transpose())




[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 3 5 7]
 [2 4 6 8]]


In [23]:
marks = 95

if marks >= 70:
    print('distinction')
    print('congrats..')
else:
    print('good luck next time')

distinction
congrats..


In [24]:
def print_str(p0):
    print(p0)
    print(p0)
    
    return 0

In [25]:
x = print_str('python')
print(x)

python
python
0


In [26]:
def compute_sum(p0,p1):
    s = p0+p1
    return s

In [27]:
x = compute_sum(20,30)
print(x)

50


In [28]:
n1 = int(input('get first num'))
n2 = int(input('get second num'))

x = compute_sum(n1,n2)
print(x)

get first num2
get second num6
8


In [29]:
temp_1 = int(input("Enter Temperture"))

def temp_result(temp_1):
    if temp_1 > 99:
        return("The entered temperature value {} & it is hot".format(temp_1))
    elif temp_1 < 60:
        return("The entered temperature value {} & it is cold".format(temp_1))
    elif (temp_1 >= 60) and (temp_1<= 99):
        return("The entered temperature value {} & it is just right".format(temp_1))
    

print(temp_result(temp_1))

Enter Temperture45
The entered temperature value 45 & it is cold


In [32]:
T1 = int (input("Enter the temp : "))
def Temperature (T1):
    if T1 > 99:
        T = "its hot"
    elif T1 < 60:
        T = "its moderate"
    else:
            T = "its Perfect"
    return T
Temperature(T1)

Enter the temp : 45


'its moderate'

In [31]:
temp = int(input("Enter the temperature"))
if (temp > 99) :
    print("it is hot")
elif(temp<60) :
    print("it is cold") 
elif(temp<99 and temp > 60) :
    print("it is normal")


Enter the temperature45
it is cold


In [33]:
def temperature(temp) :
    if temp>99:
        print("It is hot")
    elif temp<60:
        print("It is cold")
    elif 60<temp<=99:
        print("It is just right")
    else:
         print("ok")
    return temp

t = int(input("Enter the temperature :"))
x = temperature(t)
print(x)


Enter the temperature :45
It is cold
45


In [34]:
Mark =45
if >= 50 Mark < 60:
    print("2nd Class")
elif >= 60 Mark < 70:
    print("1st Class")
elif >= 80 Mark :
    print("Distinction")
    
else:
    print("Failed")


SyntaxError: invalid syntax (541467930.py, line 2)

In [35]:
Mark = 45
50 <= Mark < 60

False

In [36]:
tempchr = input("Input Current temperature :")
intchr = int(tempchr)


def my_temp_cond(intchr):
    if intchr < 60:
         return (intchr," It is cold")
    elif temp > 99:
         return (intchr," It is hot")
    else:
        return (intchr, "It is just about right temperature")

    
output = my_temp_cond1(intchr)
print(output)

def my_temp_cond1(intchr):
    if intchr < 60:
         return (intchr," It is cold")
    elif temp > 99:
         return (intchr," It is hot")
    else:
        return (intchr, "It is just about right temperature")

Input Current temperature :45


NameError: name 'my_temp_cond1' is not defined

In [38]:
tempchr = input("Input Current temperature :")
intchr = int(tempchr)


def my_temp_cond(intchr):
    if intchr < 60:
         return (intchr," It is cold")
    elif temp > 99:
         return (intchr," It is hot")
    else:
        return (intchr, "It is just about right temperature")

    

def my_temp_cond1(intchr):
    if intchr < 60:
         return (intchr," It is cold")
    elif temp > 99:
         return (intchr," It is hot")
    else:
        return (intchr, "It is just about right temperature")
    
output = my_temp_cond1(intchr)
print(output)

Input Current temperature :45
(45, ' It is cold')


In [37]:
def grade(marks):
    if marks >= 70:
        grade = 'Distinction'
        marks_need = 100 - marks
    elif marks >= 60 and marks < 70:
        grade = 'First Class'
        marks_need = 70 - marks
    elif marks >= 50 and marks < 60:
        grade = 'Second Class'
        marks_need = 60 - marks
        print(grade, marks_need)
    elif marks >= 35 and marks < 50:
        grade = 'Pass Class'
        marks_need = 50 - marks
    else:
        grade = 'Fail'
        ##marks_need = 35 - marks   ### error... case
    
    return ('Grade secured is {0} and you need {1} marks to reach next grade'.format(grade,marks_need))

marks = int(input("Enter the marks scored : "))
x = grade(marks)  
print(x)

Enter the marks scored : 56
Second Class 4
Grade secured is Second Class and you need 4 marks to reach next grade


In [39]:
def talking_parrot(h, t):
    
    if  t == 'y':
        if h>= 7 & h<= 20 :
            Trouble='True'
        else :
            Trouble='False'        
    else:
        Trouble='False'
    
    return(Trouble)

    
hour=int(input("Enter current time(24 hr format) :")) 
talking=input(" Enter if parrot is talking ('y'or 'n')")
    
x=talking_parrot(hour, talking)
if x=='False' :
      print("Too much trouble; be quiet")
else:
      print("Thanks for keeping quiet")


Enter current time(24 hr format) :14
 Enter if parrot is talking ('y'or 'n')y
Thanks for keeping quiet


In [44]:
import time

In [45]:
print(time.time())
time.sleep(5)
print(time.time())

1715232527.0889359
1715232532.0929909


In [46]:
help(time.time)

Help on built-in function time in module time:

time(...)
    time() -> floating point number
    
    Return the current time in seconds since the Epoch.
    Fractions of a second may be present if the system clock provides them.



In [47]:
r = range(7)  ## range object is a container of control values
print(type(r))
print(r)

<class 'range'>
range(0, 7)


In [48]:
r[0]

0

In [49]:
for num in r:
    print(num)

0
1
2
3
4
5
6


In [50]:
for num in range(10):   ###  for i = 0; i < 10; i++ of c language
    print(num)

0
1
2
3
4
5
6
7
8
9


In [51]:
mylist = list(r)
print(mylist)

[0, 1, 2, 3, 4, 5, 6]


In [52]:
s = int(input('enter start num'))
e = 100
st = 2
olist = list(range(s,e,st))
print(olist)

enter start num3
[3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]


In [53]:
help(range)

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash