In [ ]:
<table align="left" width=100%>
    <tr>
        <td width="12%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                  <b> Advanced Python Programming <br> (Day 1) </b>
                </font>
            </div>
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[Stacking](#Stacking)**
4. **[Splitting](#Splitting)**
5. **[For Loop](#loop)**

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below: (or create your own list)**<br>

list1 = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [1]:
# type your code here
import numpy as np
list1 = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]
print(list1)
list1_array = np.array(list1)
print(list1_array)


[3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]
[3.04 1.65 5.76 1.66 1.54 4.69 2.68]


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [2]:
# type your code here
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]
weights_array = np.array(weights)
weights_array = weights_array[weights_array>68]
print(weights_array)



[74.2 85.  74.  70.5 86.  82. ]


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [3]:
# type your code here
np.random.seed(23)

n10 = np.random.randint(low=20,high=40,size=10)
print(type(n10))
print(n10.shape)
print(n10)


<class 'numpy.ndarray'>
(10,)
[39 26 28 29 28 33 32 27 39 26]


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to get the fifth power of the first five positive integers
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [4]:
# type your code here
np.random.seed(42)

n10 = np.random.randint(low=20,high=40,size=10)
print(n10)
n5 = n10[0:5]
print(n5)
n5 = np.power(n5, 5)
print(n5)

[26 39 34 30 27 26 38 30 30 23]
[26 39 34 30 27]
[11881376 90224199 45435424 24300000 14348907]


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to create an array of all the odd integers from 50 to 100 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [5]:
# type your code here

n11 = np.arange(50, 100)
n11 = n11[n11%2 == 1]
print(n11)

[51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97
 99]


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [6]:
# type your code here

A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

n11_arr = np.array(A)
print(n11_arr)
n11_arr_sum = np.sum(n11_arr, axis = 0)
print('The sum of each column', n11_arr_sum)





[[ 1  4  8]
 [ 5  7  3]
 [ 9 14  2]]
The sum of each column [15 25 13]


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a code to get the element-wise remainder of an array after division by 8  
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
    
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [8]:
# type your code here

num = [42, 87, 90, 14, 32, 75, 61, 80, 92]
num_array_rem = np.array(num)
print(num_array_rem)
num_array_rem = np.remainder(num_array_rem, 8)
print(num_array_rem)



[42 87 90 14 32 75 61 80 92]
[2 7 2 6 0 3 5 0 4]


<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [9]:
# type your code here

In [10]:
array_2D = np.arange(0,20).reshape(4,5)
print(array_2D)

b = array_2D.flatten()
print(b[1:6])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[1 2 3 4 5]


<table align="left">
    <tr>
        <td width="6%">
            <img src="q../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to find common values between two arrays 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

array1 = [10, 30, 50, 60, 90]

array2 = [50, 20, 80, 125, 10, 70]

In [11]:
# type your code here

In [12]:
array1 = [10, 30, 50, 60, 90]
array2 = [50, 20, 80, 125, 10, 70]

np.intersect1d(array1, array2)
print(np.intersect1d(array1, array2))


[10 50]


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

list of weights (in kg)
weights = [57, 69, 54, 65 ,71, 62, 56]

list of heights (in m)<br>
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [13]:
# type your code here
weights = [57, 69, 54, 65 ,71, 62, 56]
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53]
np_weights = np.array(weights)
np_heights = np.array(heights)
bmi = np_weights/np_heights**2
print(bmi)
bmi = np.round(bmi,2)
print(bmi)

[22.54657648 22.53061224 19.59645812 21.46915048 26.39797739 20.9572742
 23.922423  ]
[22.55 22.53 19.6  21.47 26.4  20.96 23.92]


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to add a new column ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

array1 = [[[3, 4], [8, 2],[5, 9]]]

In [14]:
# type your code here

In [15]:
array1 = [[[3, 4], [8, 2],[5, 9]]]
a = np.array(array1)
print(a.shape)
print(a)

b = np.array([[[5,7]]])
print(b.shape)
print(b)

new_array1 = np.append(a, b, axis = 1)
print(new_array1)


(1, 3, 2)
[[[3 4]
  [8 2]
  [5 9]]]
(1, 1, 2)
[[[5 7]]]
[[[3 4]
  [8 2]
  [5 9]
  [5 7]]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a code to print the identity matrix of order 5</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [16]:
# type your code here
import numpy as np
a = np.identity(5)
print(a)




[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [17]:
# type your code here
M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

np_M = np.array(M)
print(np_M.shape)
print(np_M)
np_M_T = np_M.transpose()
print('Transpose')
print(np_M_T)





(4, 4)
[[15 17 45 56]
 [ 7 42 15 63]
 [54  3 61 41]
 [ 0 87 16 20]]
Transpose
[[15  7 54  0]
 [17 42  3 87]
 [45 15 61 16]
 [56 63 41 20]]


<a id="Stacking"> </a>
## 3. Stacking

<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to combine the two arrays vertically</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**<br>

A1 = [[5, 9], [7, 6]]

A2 = [[8,-7], [0,4]]

Combine the array A2 with A1

In [20]:
# type your code here
A1 = [[5, 9], [7, 6]]
A2 = [[8,-7], [0,4]]

print(np.vstack((A2, A1)))





[[ 8 -7]
 [ 0  4]
 [ 5  9]
 [ 7  6]]


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

A1 = [[-81, 75, 40], [27, 67, 52]]

A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [21]:
# type your code here

A1 = [[-81, 75, 40], [27, 67, 52]]
A2 = [[15, 54], [39, 56]]

print(np.hstack((A2, A1)))




[[ 15  54 -81  75  40]
 [ 39  56  27  67  52]]


<a id="Splitting"> </a>
## 4. Splitting

<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a code to divide the array into three sub-arrays containing an
                       equal number of rows</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [22]:
# type your code here
A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]
np_A = np.array(A)
b = np.vsplit(np_A,3)
print(b)




[array([[ 4,  7],
       [ 2, -3]]), array([[8, 1],
       [0, 9]]), array([[ 5, -1],
       [ 8,  3]])]


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Write a program to divide the array into two sub-arrays containing an equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [23]:
# type your code here

B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]
np_B=np.array(B)
b = np.hsplit(np_B,2)
print(b)


[array([[ 8,  7],
       [ 2, -3],
       [ 8,  5]]), array([[ 0,  9],
       [ 5, 10],
       [-1,  3]])]


<a id="loop"> </a>
## 5. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Write a program to perform one-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

L1 = [45, 67, 56, 71, 54, 62, 56]

L2 = [21, 52, 64, 10, 49, 74, 26]

In [24]:
# type your code here

import numpy as np


L1 = [45, 67, 56, 71, 54, 62, 56]
L2 = [21, 52, 64, 10, 49, 74, 26]

np_L1 = np.array(L1)
np_L2 = np.array(L2)

mapping_list = list(zip(np_L1, np_L2))

print(mapping_list)
for items in mapping_list:
    print(items)



[(45, 21), (67, 52), (56, 64), (71, 10), (54, 49), (62, 74), (56, 26)]
(45, 21)
(67, 52)
(56, 64)
(71, 10)
(54, 49)
(62, 74)
(56, 26)


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Define a for loop to apply the function (2x-1)/(x+5) on every element of an array </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**
    
numbers = [6, 5, 3, 15]

In [25]:
# type your code here
numbers = [6, 5, 3, 15]

np_numbers = np.array(numbers)

a = 2 * np_numbers     
print(a)
b = np_numbers + 5
print(b)

print((a -1)/(b))

for x in np_numbers:
    print((2*x-1)/(x+5))


[12 10  6 30]
[11 10  8 20]
[1.    0.9   0.625 1.45 ]
1.0
0.9
0.625
1.45


<table align="left">
    <tr>
        <td width="6%">
            <img src="../images/RA_Logo.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>20. Write a program to change values in the array with the corresponding square root values</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**
    
num = [49, 81, 64, 25, 121, 1]

**The output should be:**

num = [7, 9, 8, 5, 11, 1]

In [26]:
# type your code here
import numpy as np
num = [49, 81, 64, 25, 121, 1]

np_num = np.array(num)
np_num = np_num ** (1/2)
num = []
for item in np_num:
    num.append(int(item))
print(num)    

[7, 9, 8, 5, 11, 1]


In [27]:
import numpy as np

n = np.arange(11.5,99.5,0.5)
print(n)

[11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.
 18.5 19.  19.5 20.  20.5 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.
 25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5 30.  30.5 31.  31.5 32.
 32.5 33.  33.5 34.  34.5 35.  35.5 36.  36.5 37.  37.5 38.  38.5 39.
 39.5 40.  40.5 41.  41.5 42.  42.5 43.  43.5 44.  44.5 45.  45.5 46.
 46.5 47.  47.5 48.  48.5 49.  49.5 50.  50.5 51.  51.5 52.  52.5 53.
 53.5 54.  54.5 55.  55.5 56.  56.5 57.  57.5 58.  58.5 59.  59.5 60.
 60.5 61.  61.5 62.  62.5 63.  63.5 64.  64.5 65.  65.5 66.  66.5 67.
 67.5 68.  68.5 69.  69.5 70.  70.5 71.  71.5 72.  72.5 73.  73.5 74.
 74.5 75.  75.5 76.  76.5 77.  77.5 78.  78.5 79.  79.5 80.  80.5 81.
 81.5 82.  82.5 83.  83.5 84.  84.5 85.  85.5 86.  86.5 87.  87.5 88.
 88.5 89.  89.5 90.  90.5 91.  91.5 92.  92.5 93.  93.5 94.  94.5 95.
 95.5 96.  96.5 97.  97.5 98.  98.5 99. ]


In [28]:
help(str.isnumeric)

Help on method_descriptor:

isnumeric(self, /)
    Return True if the string is a numeric string, False otherwise.
    
    A string is numeric if all characters in the string are numeric and there is at
    least one character in the string.



In [29]:
"20".isdecimal()

True

In [30]:
help(str.isidentifier)

Help on method_descriptor:

isidentifier(self, /)
    Return True if the string is a valid Python identifier, False otherwise.
    
    Call keyword.iskeyword(s) to test whether string s is a reserved identifier,
    such as "def" or "class".

